---

- name: create-end | report that the creation of the node is finished
  uri:
    url: "http://{{ consul }}:{{ consul_port }}/v1/kv/{{ cluster_name }}/.create/{{ ansible_hostname }}/ongoing"
    method: DELETE
    status_code: 200
  register: create_end
  until: create_end.failed == false
  delay: 1
  retries: 30
