---

- import_tasks: ssh-keys-bootstrap.yml
  when: ssh_keys_enabled == "true"
  tags: bootstrap

- import_tasks: ssh-keys.yml
  when: ssh_keys_enabled == "true"

- import_tasks: others-wait.yml
  tags: others

- import_tasks: provisioner-role.yml
  when: provisioner_role_enabled == "true"

- import_tasks: bootstrap-end.yml
  tags: bootstrap
