---

- name: others-wait | wait until bootstrap node ends all the tasks
  uri:
    url: "http://{{ consul }}:{{ consul_port }}/v1/kv/{{ consul_path }}/custom_bootstrap_end"
    method: GET
    status_code: 200
    body: '{ "name": {{ ansible_hostname }}.node.{{ consul_datacenter }}.consul }'
    body_format: json
  register: bootstrap_wait
  until: bootstrap_wait.failed == false
  delay: 1
  retries: 6000
