---

- name: provisioner-role | create requirement file for provisioner ansible role
  copy:
    content: |
      - src: {{ provisioner_role }}
        version: {{ provisioner_role_version }}
        name: provisioner_role
    dest: provisioner_role_requirement.yml
  delegate_to: localhost

- name: provisioner-role | ensure roles directory exist
  file: path=roles state=directory
  delegate_to: localhost

- name: "provisioner-role | install role {{ provisioner_role }}"
  command: ansible-galaxy install -r provisioner_role_requirement.yml -p roles
  args:
    creates: roles/provisioner_role
  delegate_to: localhost

- include_role:
    name: provisioner_role
    public: yes
